version: "3.1"
services:
  es:
    hostname: es
    image: 172.29.250.56:8089/akso/es6.7.1:20210517152613
    restart: always
    # volumes:
    #   - /home/es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "0.0.0.0:9200:9200"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - parakeet
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:6.7.1
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - parakeet
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.8.19-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=akso
    ports:
      - "15672:15672"
      - "5672:5672"
    # volumes:
    #   - /home/rabbitmq:/var/lib/rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - parakeet
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - parakeet
  mysql:
    hostname: mysql
    image: 172.29.250.56:8089/akso/mysql:8.0.19
    command:
      --default-authentication-plugin=mysql_native_password
      --innodb-doublewrite=0
      --lower-case-table-names=1
      --innodb-page-size=64K
    ports: 
      - 3306:3306
    volumes:
      - D:/Database/mysql:/var/lib/mysql
    networks: 
      - parakeet    
    environment:
      MYSQL_ROOT_PASSWORD: Eqms123456
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  parakeet:
